mach_nix/run.py
Since commit fa2bb2d33fb9b9dc3113046e4fcc16088f56981a, the nix-build
subprocess is called without `capture_output=True`. Therefore, proc.stderr
is None. The subprocess stderr is already being dumped to stderr, so
there is no need for doing a print.
=> Fix AttributeError when nix-build fails

Changelog.md, Readme.md, examples.md, mach_nix/generate.py, mach_nix/generators/overides_generator.py
Fix broken wheel packages
- Some wheel packages could brake through patchelf if they already contained stripped binaries. Packages like numpy wouldn't work because of this. This is now fixed by passing `dontStrip` to the `autoPatchelf` routine.
=> Release 2.1.1

mach_nix/generators/overides_generator.py
Some packages such as ["zope.interface"](https://pypi.org/project/zope.interface/) contain characters that have a special meaning in Nix if they're not quoted.
=> Always quote package names

examples.md
I was getting the following error when copying this part from [examples.md](https://github.com/DavHau/mach-nix/blob/master/examples.md#import-mach-nix):
```sh
$ nix-shell
couldn't find remote ref heads/refs/2.3.0
error: program 'git' failed with exit code 128
```
Thought something went wrong with the project, but using the example from [README.md](https://github.com/DavHau/mach-nix#basic) works. So fix in `example.md` file too.
=> Fix ref in examples

default.nix, flake.lock, flake.nix
1. `nix-env -iA nixpkgs.nixFlakes`
2. 
```console
$ cat ~/.config/nix/nix.conf
experimental-features = nix-command flakes
```
3. `nix shell --show-trace`
<details>
```console
$ nix shell --show-trace
while evaluating the attribute 'packages.mach-nix.mach-nix' at /nix/store/g75adbd9wjxcvlm7mxykc135jz7cljz0-source/default.nix:21:3:
while evaluating anonymous function at /nix/store/g75adbd9wjxcvlm7mxykc135jz7cljz0-source/mach_nix/nix/python.nix:1:1, called from /nix/store/g75adbd9wjxcvlm7mxykc135jz7cljz0-source/default.nix:3:12:
while evaluating anonymous function at /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/pkgs/top-level/impure.nix:15:1, called from /nix/store/g75adbd9wjxcvlm7mxykc135jz7cljz0-source/default.nix:2:10:
while evaluating anonymous function at …
```
=> chore: package as nix flake

default.nix
setuptools allows for install_requires and setup_requires to be either a
string or list of strings. This commit ensures the two formats are
normalised to a list.
https://setuptools.readthedocs.io/en/latest/userguide/keywords.html#id7
For reference, I encountered this when trying to build elastalert with the following derivation:
```nix
let
mach-nix = import (builtins.fetchGit {
url = "https://github.com/DavHau/mach-nix/";
ref = "refs/tags/2.4.1";
});
in
mach-nix.buildPythonPackage {
src = builtins.fetchGit {
url = "https://github.com/Yelp/elastalert";
ref = "refs/tags/0.2.4";
rev = "7d369e41fb00127ac278a911dd8025906be46738";
};
}
```
=> fix: allow for string setup/install_requires

Readme.md
As per #132 not supported are, at the time of writing:
- poetry (project.toml)
- poetry (poetry.lock)
- PEP 518
- Pipenv
---
It has taken me quite a while, including going through cryptic error messages, to find out that `pyproject.toml` based builds are not supported by the current extractors. This hint might help future readers to save on that journey.
=> readme: clarify that not all sources can be built

mach_nix/data/providers.py
The original error message still references the deprecated way of setting the version of `pypi-deps-db`.
This PR fixes that and makes some improvements in the error message text/formatting.
=> Fix outdated error message that is presented when pypy-deps-db is outdated

Readme.md
The README example didn't work, due to an incorrect git ref.
It now works with this commit.
=> README: refs/heads/{version} -> refs/tags/

mach_nix/data/providers.py, mach_nix/tests/test_providers.py
https://www.python.org/dev/peps/pep-0600/
This fixes e.g. using the latest tokenizers package (0.10.3) with
mach-nix.
TODO: Update WheelDependencyProvider to process all filename tags
individually instead of matching them all with a single regexp. If it
had done that already, this change would have been somewhat unneeded, as
all wheel files seem to be doubly tagged (at least for now):
* manylinux_2_5 is also tagged manylinux1
* manylinux_2_12 is also tagged manylinux2010
* manylinux_2_17 is also tagged manylinux2014
(But since the new format is first in the filename, the old regexps
don't match.)
Fixes https://github.com/DavHau/mach-nix/issues/300.
--
@DavHau: I grepped the repo for `manylinux`, found some tests, added two test cases for the new format and hacked the source until the …
=> Add support for manylinux_${GLIBCMAJOR}_${GLIBCMINOR} wheels

Readme.md, examples.md, pypi-crawlers/nix/python.nix
The patch is silly, but I hope the argumentation makes some sense.
I've been struggling a while to find out what was going on as even the most basic example like
```
let
mach-nix = import (builtins.fetchGit {
url = "https://github.com/DavHau/mach-nix/";
ref = "refs/tags/3.3.0";
}) {};
in
mach-nix.mkPython {
requirements = ''
pillow
numpy
requests
'';
}
``` 
wasn't working for me and I got a weird git error.
In my .gitconfig I had:
```
[url "git@github.com:"]
insteadOf = https://github.com/
```
I did some checks and:
`git clone git@github.com:DavHau/mach-nix` ✅ 
`git clone git@github.com:DavHau/mach-nix.git` ✅ 
`git clone git@github.com:DavHau/mach-nix/`  🔴  
`git clone https://github.com/DavHau/mach-nix` ✅ 
`git clone https://github.com/DavHau/mach-nix.git` ✅ 
`git clone …
=> Remove trailing slash in mach-nix git url

Readme.md
The providers are numbered.  It probably doesn't help much to announce the total at the top.
=> remove the outdated count of supported providers

mach_nix/requirements.py
Here's a straw-man.  It makes builds with requirements with direct references "work" (by just ignoring the direct reference completely).
Relates to #352
=> Ignore direct references in requirements

examples.md
It seems there is no documentation on how to use mach-nix with Flakes. Looking a bit around the issues and `flake.nix`, I think this is the right way. If one wants to override pypi deps, I am a bit unsure what the right solution is. I don't know if it's worth putting it in the documentation. If yes, I suppose this is:
```nix
inputs = {
nixpkgs.url = "github:nixos/nixpkgs";
flake-utils.url = "github:numtide/flake-utils";
pypi-deps-db = {
url = github:DavHau/pypi-deps-db/99799f6300b2dc4a4063dc3da032f5f169709567;
flake = false;
};
mach-nix = {
url = "github:DavHau/mach-nix?ref=3.3.0";
inputs = {
nixpkgs.follows = "nixpkgs";
flake-utils.follows = "flake-utils";
pypi-deps-db.follows = "pypi-deps-db";
};
};
}
```
From my understanding, the default values already contain reference to inputs.
=> Add an example using a Flake

lib/extractor/default.nix
This causes dependency extraction to fail on python2, with nixos-21.11.
=> Remove the dependency on python pkgconfig package in the dependency extractor.

mach_nix/data/providers.py
e.g. `numpy-1.21.4-cp310-cp310-macosx_11_0_arm64.whl`  https://pypi.org/project/numpy/#files
=> Match macosx_11_0_arm64.wheel

mach_nix/data/nixpkgs.py, mach_nix/data/providers.py, mach_nix/nix/mkPython.nix, mach_nix/nix/nixpkgs-json.nix
Otherwise, it is likely that there will be collisions building the python environment,
as the dependencies of packages in packagesExtra won't match with the dependencies
calculated by mach-nix.
As a side-effect, this also causes the dependencies of mach-nix built packages included
by the `nixpkgs` provider to be included in dependency resolution.
=> Update dependencies of python packages specified in packagesExtra in mkPython.

mach_nix/fixes.nix
fixes an error that has recently emerged for me:
```
error: builder for '/nix/store/slbbyvcpivzj9inwi0mq1vkaa6qypc77-py-eval-result.drv' failed with exit code 1;
last 6 log lines:
> Traceback (most recent call last):
>   File "<string>", line 2, in <module>
>   File "/nix/store/k07820lv55ziin5v4v9h91rah86qh7qq-python3.9-packaging-21.3/lib/python3.9/site-packages/packaging/version.py", line 42
>     def parse(version: str) -> Union["LegacyVersion", "Version"]:
>                      ^
> SyntaxError: invalid syntax
For full logs, run 'nix log /nix/store/slbbyvcpivzj9inwi0mq1vkaa6qypc77-py-eval-result.drv'.
```
=> use pkgs.python3 instead of pkgs.python(2)

flake.nix, git-hooks/pre-commit, mach_nix/VERSION, mach_nix/data/providers.py, mach_nix/deptree.py, mach_nix/flake.lock, mach_nix/generators/overides_generator.py, mach_nix/nix/CONDA_CHANNELS.json, mach_nix/nix/compileOverrides.nix, mach_nix/nix/lib.nix, mach_nix/nix/python.nix, mach_nix/nix/update-deps.sh, mach_nix/resolver/__init__.py, mach_nix/resolver/resolvelib_resolver.py
This improves the previously introduced dependency removal of packages from provider `nixpkgs`.
It was originally introduced to fight package collision issues but seemed to remove too many dependencies in many situation.
Now this mechanism gets a little more conservative. Dependencies are only removed if the dependency tree of the current package is known from the sdist DB and we can say for sure that certain dependencies is not needed.
Also inputs nixpkgs, pypi-deps-db, conda-channels are updated
fixes https://github.com/DavHau/mach-nix/issues/346
fixes https://github.com/DavHau/mach-nix/issues/330
=> Fix unwanted dependency removal; update nixpkgs + deps-db

.github/workflows/CI_NixPy.yml, flake.nix, tests/all-tests.nix, tests/execute.sh, tests/make-tests.nix, tests/test_py38_cp38_wheel.nix
- Don't use a prerelease version of nix in CI (and stop installing two different copies of nix).
- Split CI into multiple jobs, to improve end-to-end time. This also, incidentally, ensures that tests don't fail silently.
- Start running the tests with conda as a provider in CI.
- It looks like this was accidentally removed in 9463ccc8c7a5ce085d3cea36685d6b58d9bc90e0 which landed as part of #285.
- Fix the invocation of unit-tests in CI, which was failing silently.
=> Improve CI.

mach_nix/data/providers.py, mach_nix/deptree.py, mach_nix/generators/overides_generator.py, mach_nix/nix/python-deps.nix, mach_nix/resolver/__init__.py, mach_nix/resolver/resolvelib_resolver.py, setup.py
resolvelib is on 0.8.1, but I'm only upgrading one step here, to make it easier to deal with breaking changes.
=> Upgrade resolvelib to 0.4.0.

mach_nix/data/providers.py, mach_nix/deptree.py, mach_nix/generators/overides_generator.py, mach_nix/resolver/__init__.py, mach_nix/resolver/resolvelib_resolver.py
While working on #334, I discovered that provider logic was doing a bunch of duplicate work because it wasn't preserving data it already had. This preserves the provider-known version (which is what `deviated_version` was calculating), as well as the raw package data from the provider, which is used for calculating requirements, without having to re-find the package.
I *think* this changes what conda build gets picked, it should now always pick the highest matching build number. I think previously it was random, if there were no build restrictions, and the *lowest* if there were restrictions.
=> Track raw provider version, rather than rebuilding.

mach_nix/deptree.py, mach_nix/nix/conda-channels.nix, mach_nix/nix/lib.nix
Adds some aarch64-darwin compatibility fixes that I ran into on our own code.
The deptree thing would result in an error like #396 
```
....
File "/nix/store/585x19x0hkzvnd6nai6ag5hpnl8zajh1-jrpk0l8ad8wrak6yhgfmraddnpia4vpd-source/mach_nix/deptree.py", line 78, in name
if indexed_pkgs[node_name].build_inputs + indexed_pkgs[node_name].prop_build_inputs == []:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
```
Fixes #396 
Let's see if this also fixes the odd conda errors in CI.
=> Add aarch64-darwin to the system map for conda channels. Fix darwin manylinux logic. Fix deptree NoneType + NoneType

default.nix
Fixes #385.
This check might be broken by https://github.com/NixOS/nix/issues/5970 in the future. (Although the suggestion in https://github.com/NixOS/nix/pull/5971#issuecomment-1021695124) would address that in new enough versions of nix.)
=> Add a nix version check.

mach_nix/fixes.nix
Without this the package fails to build. (It is only distributed as a tarball for non-macOS it seems.)
=> fix-package: pyjq needs nativeBuildInputs

lib/extractor/default.nix
[I don't see a way to adapt pipenv to the python version the user asked for, since some use of base_derivation is used by _multiple_ python versions. Hence I think it's better to remove pipenv.]
This fixes automatic dependency extraction from packages when the user
asks for a python version that differs too much from the default python
in nixpkgs (which pipenv was built with).
Fixes https://github.com/DavHau/mach-nix/issues/426.
=> Remove pipenv from dependency extractor derivation

.gitignore, .gitpod.yml, .vscode/extensions.json, .vscode/settings.json, Readme.md, setup.py
Just click on the readme badge and get into a full development
environment with python, pytest and test debugging integration.
=> feat: support Gitpod

Readme.md, implementation.md
fix #434
maybe a bit too verbose ...
maybe belongs to `eli5.md` ; )
=> add section: File resolution (#434)

mach_nix/nix/mkPython.nix
Since
https://github.com/NixOS/nixpkgs/commit/7f802c704651baba3adb2abdd9cc6645c987b9ad
using --suffix-each in makeWrapperArgs is no longer supported and breaks
like this:
```
$ nix-build ./any-mach-nix-env-with-latest-nixpkgs.nix
[...]
<stdin>: In function 'main':
<stdin>:9:6: error: #error makeCWrapper: Unknown argument --suffix-each
<stdin>:10:6: error: #error makeCWrapper: Unknown argument PATH
<stdin>:11:6: error: #error makeCWrapper: Unknown argument :
<stdin>:12:6: error: #error makeCWrapper: Unknown argument
builder for '/nix/store/41713mrzrqlq12kgfgcx10wmdvmkfh7k-python3-3.9.12-env.drv' failed with exit code 1
```
So replace it with multiple --suffix args, which the new
makeBinaryWrapper/makeCWrapper program supports (and is compatible with
the old makeWrapper).
Fixes …
=> Replace --suffix-each with multiple --suffix options

mach_nix/data/providers.py, mach_nix/tests/test_providers.py
I know this PR was closed previously - but merging it into current master helps me resolve some wheels (dvc + streamlit) which don't resolve on current master.
It also contains a valuable test to ensure that 3.10 packages resolve as intended which I think makes sense to keep
=> fix regex for 2-digit minor python version

mach_nix/nix/withDot.nix
`nix (build|shell) mach-nix#gen` is broken on recent nix versions because
of https://github.com/NixOS/nix/issues/6690.
This commit fixes it by removing `meta` from the list of handled packages.
As a result, nix can access the derivation's meta as expected, and work
as expected.
The side effect is that the `meta` package on pypi cannot be used, but
that's a cost we have to pay.
=> Fix `nix (build|shell) mach-nix#gen`

mach_nix/data/providers.py, mach_nix/nix/buildPythonPackage.nix, mach_nix/nix/mkPython.nix, mach_nix/resolver/__init__.py
I saw some typo while using `mach-nix`, but I think that particular one is fixed already, in the process of looking some came up:
Fixes some trivial typos, mostly in comments,
except for in `mach_nix/resolver/__init__.py`,
the scope is a context manager, so there shouldn't be arbitrary sideffects by the rename.
=> fix: typos

Readme.md, implementation.md, lib/extractor/default.nix, mach_nix/generators/overides_generator.py, mach_nix/nix/deps-db-and-fetcher.nix, pypi-crawlers/Readme.md, pypi-crawlers/nix/crawler/configuration.nix, pypi-crawlers/nix/power-wheels-crawler/configuration.nix, pypi-crawlers/src/crawl_sdist_deps.py
Fixes #535 
All I did was find all occurrences of nix-pypi-fetcher and replace them with nix-pypi-fetcher-2.  I don't really understand all of the interactions with this value (I'm particularly unclear on the git revisions that appear some of these values - why can't I find them on github and why can I change the repository without changing the revision?)
The result appears to work.  With HEAD of this branch and pypi-deps-db 5440c9c76f6431f300fb6a1ecae762a5444de5f6 I can build tahoe-lafs/tahoe-lafs ~af10f96ef729b12dcbacdc0b5dd7f4750ff0b942~ 96d783534a986e2bca9ef5a00e99240aa2232c88 whereas with mach-nix 68a85753555ed67ff53f0d0320e5ac3c725c7400 and pypi-deps-db 5440c9c76f6431f300fb6a1ecae762a5444de5f6 I get the error in the referenced ticket.
=> unthinkingly substitute the new fetcher everywhere

mach_nix/flake.lock
It seems the old flake dependency to `pypi-deps-db` is too old, and refers to a now non-existent commit of `nix-pypi-fetcher-2`. 
Therefore, trying to build any python package using the `wheel` provider will fail with:
```
at /nix/store/hqqb9ddw62wwm8sx3splqgzwpcvrcyai-mach_nix_file/share/mach_nix_file.nix:11:17:
10|   };
11|   pypiFetcher = import pypi_fetcher_src { inherit pkgs; };
|                 ^
12|   fetchPypi = pypiFetcher.fetchPypi;
error: unable to download 'https://github.com/DavHau/nix-pypi-fetcher-2/tarball/d93c6f30f09599e9df96b6cd345f47ce7c172136': HTTP error 404
response body:
404: Not Found
```
Updating that dependency seems to fix this.
=> Update pypi-deps-db version

mach_nix/fixes.nix, mach_nix/nix/lib.nix
`asyncio` becomes a built-in Python library since Python 3.4. The old `asyncio` package is incompatible with Python 3.7. See https://stackoverflow.com/questions/51196568/create-task-asyncio-async-syntaxerror-invalid-syntax
=> Add deepspeed-mii.remove-asyncio to fixes

mach_nix/nix/mkPython.nix
Currently ignoreCollisions does not take effect because it is not overriding the python wrapper. This PR call `override` immediately after `withPackages`, letting ignoreCollisions take effect
=> Let ignoreCollisions take effect

mach_nix/nix/python-deps.nix
This PR added the `setuptools` dependency for `distlib` because newer `nixpkgs` does not provide `setuptools` for Python libraries by default
=> Add setuptools dependency for distlib

mach_nix/data/nixpkgs.py, mach_nix/generators/overides_generator.py, mach_nix/requirements.py
This fixes #529, by not writing out the overrides for setuptools & pip in mach_nix-file.nix.
I feel rather unsure about this fix, guidance would be nice :).
=> Fix infinite recursion when pip/setuptools is involved

mach_nix/generate.py, mach_nix/nix/python-deps.nix, setup.py
This makes mach-nix python exceptions look like this,
capturing locals at every part of the stack,
hopefully helping with the postmortem debug-ability.
Note that rich is already in the nixpkgs mach-nix uses.
=> Add Rich exceptions including locals with rich.traceback

lib/extractor/default.nix, mach_nix/data/providers.py
Following #564, it was discovered that pypi is also full of no longer parsing versions.
We had 'fixed' this for nixpkgs in #549 by eliminating all non-parsable versions,
this does the same for pypi (sdist & wheel) and conda.
It's a hot take, and not the best way forward I suppose, but it does make master usable for now.
=> Invalid versions outside nixpkgs

flake.nix, lib/extractor/default.nix, mach_nix/nix/buildPythonPackage.nix, mach_nix/nix/lib.nix
Another tiny quality-of-debuggers-life-improvement:
Previously, all source-extracted package requirements were stored in /nix/store/${hash}-package-requirements.
This patch fits the name (which is name-version, actually) into those path names,
and names them' ${name}-mach-nix-requirements'
=> Rename store paths for package-requirements-from-source

mach_nix/data/providers.py
For example py_zmq 17.1.1, which declares 'python!=3.0*'
when it nowadays has to be '3.0.*' (note the dot).
Mach-nix then fails to build a dependency tree.
This makes it ignore the packages, just like the WheelDependencyProvider does.
(This is the low hanging fruit in terms of bugs-until I have jupyter running again).
=> ignore packages that have broken python_requires definitions
